version: '3.7'

services:
  czsc-streamlit_1:
    image: czsc-streamlit:0.0.1
    container_name: czsc-streamlit_1
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  czsc-streamlit_2:
    image: czsc-streamlit:0.0.1
    container_name: czsc-streamlit_2
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  czsc-streamlit_3:
    image: czsc-streamlit:0.0.1
    container_name: czsc-streamlit_3
    volumes:
      - data-volume:/app/market-data
      - streamlit-config-volume:/app/.streamlit
    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "8500:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - czsc-streamlit_1
      - czsc-streamlit_2
      - czsc-streamlit_3

volumes:
  data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/data/czsc_streamlit-data'
  streamlit-config-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:/data/czsc_streamlit-config'